-- AlterTable
ALTER TABLE "Map" ADD COLUMN     "center" DECIMAL(65,30)[] DEFAULT ARRAY[0, 0]::DECIMAL(65,30)[],
ADD COLUMN     "maxZoom" INTEGER NOT NULL DEFAULT 14,
ADD COLUMN     "minZoom" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN     "zoom" INTEGER NOT NULL DEFAULT 10;
