version: "3"
services:
  prisma-migrate:
    container_name: prisma-migrate
    build:
      context: .
      dockerfile: Dockerfile.migrate
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      DB_PORT: 5432
    ports:
      - ${DB_PORT}:5432
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./gis.sh:/docker-entrypoint-initdb.d/gis.sh

volumes:
  postgres:
    name: map-db
