// model MarkerGroup {
//     title      String
//     gameSlug   String?
//   }
export const markerGroups = [
  { slug: "bmw_locations", title: "Locations", gameSlug: "black-myth-wukong" },
  { slug: "bmw_key_items", title: "Key Items", gameSlug: "black-myth-wukong" },
  { slug: "bmw_items", title: "Items", gameSlug: "black-myth-wukong" },
  { slug: "bmw_equipment", title: "Equipment", gameSlug: "black-myth-wukong" },
  { slug: "bmw_enemies", title: "Enemies", gameSlug: "black-myth-wukong" },
  { slug: "bmw_quests", title: "Quests", gameSlug: "black-myth-wukong" },
  { slug: "bmw_other", title: "Other", gameSlug: "black-myth-wukong" },
  { slug: "bmw_materials", title: "Materials", gameSlug: "black-myth-wukong" },
  { slug: "er_locations", title: "Locations", gameSlug: "elden-ring" },
  { slug: "er_key_items", title: "Key Items", gameSlug: "elden-ring" },
  { slug: "er_items", title: "Items", gameSlug: "elden-ring" },
  { slug: "er_equipment", title: "Equipment", gameSlug: "elden-ring" },
  { slug: "er_npcs", title: "NPCs", gameSlug: "elden-ring" },
  { slug: "er_enemies", title: "Enemies", gameSlug: "elden-ring" },
  { slug: "er_materials", title: "Materials", gameSlug: "elden-ring" },
  { slug: "er_other", title: "Other", gameSlug: "elden-ring" },
  { slug: "totk_locations", title: "Locations", gameSlug: "totk" },
  { slug: "totk_services", title: "Services", gameSlug: "totk" },
  { slug: "totk_collectibles", title: "Collectibles", gameSlug: "totk" },
  { slug: "totk_loot", title: "Loot", gameSlug: "totk" },
  { slug: "totk_quests", title: "Quests", gameSlug: "totk" },
  { slug: "totk_enemies", title: "Enemies", gameSlug: "totk" },
  { slug: "totk_other", title: "Other", gameSlug: "totk" },
  { slug: "totk_ore_deposits", title: "Ore Deposits", gameSlug: "totk" },
  { slug: "totk_materials", title: "Materials", gameSlug: "totk" },
  { slug: "totk_creatures", title: "Creatures", gameSlug: "totk" },
  { slug: "w3_locations", title: "Locations", gameSlug: "witcher-3" },
  { slug: "w3_services", title: "Services", gameSlug: "witcher-3" },
  { slug: "w3_quests", title: "Quests", gameSlug: "witcher-3" },
  { slug: "w3_items", title: "Items", gameSlug: "witcher-3" },
  { slug: "w3_other", title: "Other", gameSlug: "witcher-3" },
];
