// model MarkerCategory {
//     title         String           @default("")
//     icon          String
//     template      String?
//     info          String?
//      groupSlug
//   }
export const markerCategories = [
  { groupSlug: "bmw_locations", title: "Keeper Shrine" },
  { groupSlug: "bmw_locations", title: "Meditation Spot" },
  { groupSlug: "bmw_locations", title: "Point of Interests" },
  { groupSlug: "bmw_key_items", title: "Awaken Wine Worm" },
  { groupSlug: "bmw_key_items", title: "Celestial Pill" },
  { groupSlug: "bmw_key_items", title: "Drink" },
  { groupSlug: "bmw_key_items", title: "Formula" },
  { groupSlug: "bmw_key_items", title: "Gourd" },
  { groupSlug: "bmw_key_items", title: "Key Items" },
  { groupSlug: "bmw_key_items", title: "Luojia Fragrant Vine" },
  { groupSlug: "bmw_key_items", title: "Soak" },
  { groupSlug: "bmw_key_items", title: "Spirit" },
  { groupSlug: "bmw_items", title: "Chests" },
  { groupSlug: "bmw_items", title: "Will" },
  { groupSlug: "bmw_equipment", title: "Armor Set" },
  { groupSlug: "bmw_equipment", title: "Curio" },
  { groupSlug: "bmw_equipment", title: "Spell" },
  { groupSlug: "bmw_equipment", title: "Transformation Spell" },
  { groupSlug: "bmw_equipment", title: "Vessel" },
  { groupSlug: "bmw_equipment", title: "Staff" },
  { groupSlug: "bmw_enemies", title: "Elite Lesser Yaoguai" },
  { groupSlug: "bmw_enemies", title: "Lesser Yaoguai" },
  { groupSlug: "bmw_enemies", title: "Yaoguai Chief" },
  { groupSlug: "bmw_enemies", title: "Yaoguai King" },
  { groupSlug: "bmw_quests", title: "Encounters" },
  { groupSlug: "bmw_other", title: "Easter Eggs" },
  { groupSlug: "bmw_other", title: "Misc" },
  { groupSlug: "bmw_other", title: "NPC" },
  { groupSlug: "bmw_materials", title: "Aged Ginseng" },
  { groupSlug: "bmw_materials", title: "Fire Bellflower" },
  { groupSlug: "bmw_materials", title: "Fragrant Jade Flower" },
  { groupSlug: "bmw_materials", title: "Jade Lotus" },
  { groupSlug: "bmw_materials", title: "Licorice" },
  { groupSlug: "bmw_materials", title: "Millenium Ginseng" },
  { groupSlug: "bmw_materials", title: "Nine-Capped Lingzhi" },
  { groupSlug: "bmw_materials", title: "Purple Lingzhi" },
  { groupSlug: "er_locations", title: "Divine Tower" },
  { groupSlug: "er_locations", title: "Dragon Shrine" },
  { groupSlug: "er_locations", title: "Dungeon" },
  { groupSlug: "er_locations", title: "Elevator" },
  { groupSlug: "er_locations", title: "Evergaol" },
  { groupSlug: "er_locations", title: "Hidden Passage" },
  { groupSlug: "er_locations", title: "Imp Seal Statue" },
  { groupSlug: "er_locations", title: "Landmarks" },
  { groupSlug: "er_locations", title: "Legacy Dungeon" },
  { groupSlug: "er_locations", title: "Martyr Effigy" },
  { groupSlug: "er_locations", title: "Minor Erdtree" },
  { groupSlug: "er_locations", title: "Portal" },
  { groupSlug: "er_locations", title: "Site of Grace" },
  { groupSlug: "er_locations", title: "Smithing Table" },
  { groupSlug: "er_locations", title: "Spiritspring Jump" },
  { groupSlug: "er_locations", title: "Stake of Marika" },
  { groupSlug: "er_locations", title: "Wandering Mausoleum" },
  { groupSlug: "er_key_items", title: "Bell Bearing" },
  { groupSlug: "er_key_items", title: "Cookbook" },
  { groupSlug: "er_key_items", title: "Cracked Pot" },
  { groupSlug: "er_key_items", title: "Great Rune" },
  { groupSlug: "er_key_items", title: "Map Fragment" },
  { groupSlug: "er_key_items", title: "Memory Stone" },
  { groupSlug: "er_key_items", title: "Painting" },
  { groupSlug: "er_key_items", title: "Perfume Bottle" },
  { groupSlug: "er_key_items", title: "Remembrance" },
  { groupSlug: "er_key_items", title: "Ritual Pot" },
  { groupSlug: "er_key_items", title: "Spellbook" },
  { groupSlug: "er_key_items", title: "Stonesword Key" },
  { groupSlug: "er_key_items", title: "Talisman Pouch" },
  { groupSlug: "er_key_items", title: "Tool" },
  { groupSlug: "er_key_items", title: "Whetblade" },
  { groupSlug: "er_key_items", title: "Other" },
  { groupSlug: "er_items", title: "Ammunition" },
  { groupSlug: "er_items", title: "Cerulean Scarab" },
  { groupSlug: "er_items", title: "Consumable" },
  { groupSlug: "er_items", title: "Crimson Scarab" },
  { groupSlug: "er_items", title: "Crystal Tear" },
  { groupSlug: "er_items", title: "Deathroot" },
  { groupSlug: "er_items", title: "Dragon Heart" },
  { groupSlug: "er_items", title: "Gesture" },
  { groupSlug: "er_items", title: "Golden Rune" },
  { groupSlug: "er_items", title: "Golden Seed" },
  { groupSlug: "er_items", title: "Item" },
  { groupSlug: "er_items", title: "Larval Tear" },
  { groupSlug: "er_items", title: "Multiplayer Item" },
  { groupSlug: "er_items", title: "Rune Arc" },
  { groupSlug: "er_items", title: "Sacred Tear" },
  { groupSlug: "er_items", title: "Spirit Ashes" },
  { groupSlug: "er_equipment", title: "Armor" },
  { groupSlug: "er_equipment", title: "Ash of War" },
  { groupSlug: "er_equipment", title: "Incantation" },
  { groupSlug: "er_equipment", title: "Shields" },
  { groupSlug: "er_equipment", title: "Sorcery" },
  { groupSlug: "er_equipment", title: "Talisman" },
  { groupSlug: "er_equipment", title: "Weapons" },
  { groupSlug: "er_npcs", title: "Character" },
  { groupSlug: "er_npcs", title: "Ghost" },
  { groupSlug: "er_npcs", title: "Merchant" },
  { groupSlug: "er_npcs", title: "Trainer" },
  { groupSlug: "er_enemies", title: "Boss" },
  { groupSlug: "er_enemies", title: "Elite Enemy" },
  { groupSlug: "er_enemies", title: "Enemy" },
  { groupSlug: "er_enemies", title: "Great Boss" },
  { groupSlug: "er_enemies", title: "Invasion" },
  { groupSlug: "er_enemies", title: "Legendary Boss" },
  { groupSlug: "er_materials", title: "Ancient Smithing Stone" },
  { groupSlug: "er_materials", title: "Somber Smithing Stone" },
  { groupSlug: "er_materials", title: "Crafting Material" },
  { groupSlug: "er_materials", title: "Ghost Glovewort" },
  { groupSlug: "er_materials", title: "Glovewort" },
  { groupSlug: "er_materials", title: "Great Glovewort" },
  { groupSlug: "er_materials", title: "Miquella's Lily" },
  { groupSlug: "er_materials", title: "Ruin Fragment" },
  { groupSlug: "er_materials", title: "Smithing Stone" },
  { groupSlug: "er_materials", title: "Trina's Lilly" },
  { groupSlug: "er_other", title: "Birdseye Telescope" },
  { groupSlug: "er_other", title: "Guiding Statue" },
  { groupSlug: "er_other", title: "Lores" },
  { groupSlug: "er_other", title: "Misc." },
  { groupSlug: "er_other", title: "Puzzle" },
  { groupSlug: "er_other", title: "Quest" },
  { groupSlug: "er_other", title: "Summoning Sigil" },
  { groupSlug: "er_other", title: "Stone Cairn" },
  { groupSlug: "totk_locations", title: "Area" },
  { groupSlug: "totk_locations", title: "Building" },
  { groupSlug: "totk_locations", title: "Cave" },
  { groupSlug: "totk_locations", title: "Chasm" },
  { groupSlug: "totk_locations", title: "Goddess Statue" },
  { groupSlug: "totk_locations", title: "Great Fairy" },
  { groupSlug: "totk_locations", title: "Landmark" },
  { groupSlug: "totk_locations", title: "Lighthouse" },
  { groupSlug: "totk_locations", title: "Lightroot" },
  { groupSlug: "totk_locations", title: "Point of Interest" },
  { groupSlug: "totk_locations", title: "Province" },
  { groupSlug: "totk_locations", title: "Settlement" },
  { groupSlug: "totk_locations", title: "Shrine" },
  { groupSlug: "totk_locations", title: "Skyview Tower" },
  { groupSlug: "totk_locations", title: "Tech Lab" },
  { groupSlug: "totk_locations", title: "Temple" },
  { groupSlug: "totk_locations", title: "Zonai Survey Team Base" },
  { groupSlug: "totk_services", title: "Armor Shop" },
  { groupSlug: "totk_services", title: "Bargainer Statue" },
  { groupSlug: "totk_services", title: "Crystal Refinery" },
  { groupSlug: "totk_services", title: "Device Dispenser" },
  { groupSlug: "totk_services", title: "Dye Shop" },
  { groupSlug: "totk_services", title: "General Store" },
  { groupSlug: "totk_services", title: "Hestu" },
  { groupSlug: "totk_services", title: "Inn" },
  { groupSlug: "totk_services", title: "Jewelry Shop" },
  { groupSlug: "totk_services", title: "Koltin" },
  { groupSlug: "totk_services", title: "Mini-Game" },
  { groupSlug: "totk_services", title: "Stable" },
  { groupSlug: "totk_services", title: "Travelling Merchant" },
  { groupSlug: "totk_collectibles", title: "Ancient Tablet" },
  { groupSlug: "totk_collectibles", title: "Autobuild Schematic" },
  { groupSlug: "totk_collectibles", title: "Dragon Tear" },
  { groupSlug: "totk_collectibles", title: "Key Item" },
  { groupSlug: "totk_collectibles", title: "Korok Seed" },
  { groupSlug: "totk_collectibles", title: "Master Sword" },
  { groupSlug: "totk_collectibles", title: "Paraglider Fabric" },
  { groupSlug: "totk_collectibles", title: "Sage's Will" },
  { groupSlug: "totk_collectibles", title: "Treasure" },
  { groupSlug: "totk_collectibles", title: "Yiga Schematic" },
  { groupSlug: "totk_loot", title: "Link Armor" },
  { groupSlug: "totk_loot", title: "Arrows" },
  { groupSlug: "totk_loot", title: "Blupee" },
  { groupSlug: "totk_loot", title: "Chest" },
  { groupSlug: "totk_loot", title: "Elixir" },
  { groupSlug: "totk_loot", title: "Gem" },
  { groupSlug: "totk_loot", title: "Poe" },
  { groupSlug: "totk_loot", title: "Rupees" },
  { groupSlug: "totk_loot", title: "Shield" },
  { groupSlug: "totk_loot", title: "Treasure Chest" },
  { groupSlug: "totk_loot", title: "Weapon" },
  { groupSlug: "totk_loot", title: "Zonai Charge" },
  { groupSlug: "totk_loot", title: "Zonai Component" },
  { groupSlug: "totk_quests", title: "Main Quest" },
  { groupSlug: "totk_quests", title: "Memory" },
  { groupSlug: "totk_quests", title: "Shrine Quest" },
  { groupSlug: "totk_quests", title: "Side Adventure" },
  { groupSlug: "totk_quests", title: "Side Quest" },
  { groupSlug: "totk_enemies", title: "Dragon" },
  { groupSlug: "totk_enemies", title: "Enemy Camp" },
  { groupSlug: "totk_enemies", title: "Flux Construct" },
  { groupSlug: "totk_enemies", title: "Frox" },
  { groupSlug: "totk_enemies", title: "Gleeok" },
  { groupSlug: "totk_enemies", title: "Hinox" },
  { groupSlug: "totk_enemies", title: "Lynel" },
  { groupSlug: "totk_enemies", title: "Miniboss" },
  { groupSlug: "totk_enemies", title: "Molduga" },
  { groupSlug: "totk_enemies", title: "Octorok" },
  { groupSlug: "totk_enemies", title: "Stalnox" },
  { groupSlug: "totk_enemies", title: "Stronghold" },
  { groupSlug: "totk_enemies", title: "Talus" },
  { groupSlug: "totk_enemies", title: "Wizzrobe" },
  { groupSlug: "totk_enemies", title: "Yiga" },
  { groupSlug: "totk_enemies", title: "Zonai" },
  { groupSlug: "totk_other", title: "Cave Entrance" },
  { groupSlug: "totk_other", title: "Cooking Pot" },
  { groupSlug: "totk_other", title: "Easter Egg" },
  { groupSlug: "totk_other", title: "Falling Platform" },
  { groupSlug: "totk_other", title: "Hudson Sign" },
  { groupSlug: "totk_other", title: "Lore" },
  { groupSlug: "totk_other", title: "Mechanism" },
  { groupSlug: "totk_other", title: "Other Miscellaneous" },
  { groupSlug: "totk_other", title: "NPCs" },
  { groupSlug: "totk_other", title: "Quest Objective" },
  { groupSlug: "totk_other", title: "Satori Tree" },
  { groupSlug: "totk_other", title: "Unique Horse" },
  { groupSlug: "totk_other", title: "Vehicle" },
  { groupSlug: "totk_other", title: "Well" },
  { groupSlug: "totk_ore_deposits", title: "Luminous Stone" },
  { groupSlug: "totk_ore_deposits", title: "Ore Deposit" },
  { groupSlug: "totk_ore_deposits", title: "Rare Ore Deposit" },
  { groupSlug: "totk_ore_deposits", title: "Zonaite" },
  { groupSlug: "totk_materials", title: "Ancient" },
  { groupSlug: "totk_materials", title: "Ancient Blade" },
  { groupSlug: "totk_materials", title: "Apple" },
  { groupSlug: "totk_materials", title: "Armoranth" },
  { groupSlug: "totk_materials", title: "Bird Egg" },
  { groupSlug: "totk_materials", title: "Bomb Flower" },
  { groupSlug: "totk_materials", title: "Brightbloom Seed" },
  { groupSlug: "totk_materials", title: "Chillshroom" },
  { groupSlug: "totk_materials", title: "Cool Safflina" },
  { groupSlug: "totk_materials", title: "Dazzlefruit" },
  { groupSlug: "totk_materials", title: "Electric Safflina" },
  { groupSlug: "totk_materials", title: "Endura Carrot" },
  { groupSlug: "totk_materials", title: "Fairy" },
  { groupSlug: "totk_materials", title: "Fleet-Lotus Seeds" },
  { groupSlug: "totk_materials", title: "Hearty Raddish" },
  { groupSlug: "totk_materials", title: "Hearty Truffle" },
  { groupSlug: "totk_materials", title: "Hydromelon" },
  { groupSlug: "totk_materials", title: "Ice Fruit" },
  { groupSlug: "totk_materials", title: "Material" },
  { groupSlug: "totk_materials", title: "Mighty Bananas" },
  { groupSlug: "totk_materials", title: "Mighty Thistle" },
  { groupSlug: "totk_materials", title: "Razorshroom" },
  { groupSlug: "totk_materials", title: "Rushroom" },
  { groupSlug: "totk_materials", title: "Shock Fruit" },
  { groupSlug: "totk_materials", title: "Silent Princess" },
  { groupSlug: "totk_materials", title: "Skyshroom" },
  { groupSlug: "totk_materials", title: "Spicy Pepper" },
  { groupSlug: "totk_materials", title: "Stamella Shroom" },
  { groupSlug: "totk_materials", title: "Swift Carrot" },
  { groupSlug: "totk_materials", title: "Voltfruit" },
  { groupSlug: "totk_materials", title: "Warm Safflina" },
  { groupSlug: "totk_materials", title: "Wildberry" },
  { groupSlug: "totk_materials", title: "Zapshroom" },
  { groupSlug: "totk_creatures", title: "Animal" },
  { groupSlug: "totk_creatures", title: "Armored Porgy" },
  { groupSlug: "totk_creatures", title: "Bladed Rhino Beetle" },
  { groupSlug: "totk_creatures", title: "Bright-Eyed Crab" },
  { groupSlug: "totk_creatures", title: "Cold Darner" },
  { groupSlug: "totk_creatures", title: "Donkey" },
  { groupSlug: "totk_creatures", title: "Eldin Ostrich" },
  { groupSlug: "totk_creatures", title: "Electric Darner" },
  { groupSlug: "totk_creatures", title: "Energetic Rhino Beetle" },
  { groupSlug: "totk_creatures", title: "Fireproof Lizard" },
  { groupSlug: "totk_creatures", title: "Fish" },
  { groupSlug: "totk_creatures", title: "Grassland Fox" },
  { groupSlug: "totk_creatures", title: "Grizzlemaw Bear" },
  { groupSlug: "totk_creatures", title: "Hightail Lizard" },
  { groupSlug: "totk_creatures", title: "Honeyvore Bear" },
  { groupSlug: "totk_creatures", title: "Horse" },
  { groupSlug: "totk_creatures", title: "Hotfeather Pigeon" },
  { groupSlug: "totk_creatures", title: "Hyrule Bass" },
  { groupSlug: "totk_creatures", title: "Maraudo Wolf" },
  { groupSlug: "totk_creatures", title: "Mighty Porgy" },
  { groupSlug: "totk_creatures", title: "Mountain Doe" },
  { groupSlug: "totk_creatures", title: "Razorclaw Crab" },
  { groupSlug: "totk_creatures", title: "Rugged Rhino Beetle" },
  { groupSlug: "totk_creatures", title: "Sand Seal" },
  { groupSlug: "totk_creatures", title: "Sanke Carp" },
  { groupSlug: "totk_creatures", title: "Seagull" },
  { groupSlug: "totk_creatures", title: "Smotherwing Butterfly" },
  { groupSlug: "totk_creatures", title: "Snowcoat Fox" },
  { groupSlug: "totk_creatures", title: "Sparrow" },
  { groupSlug: "totk_creatures", title: "Summerwing Butterfly" },
  { groupSlug: "totk_creatures", title: "Sunset Firefly" },
  { groupSlug: "totk_creatures", title: "Tabantha Moose" },
  { groupSlug: "totk_creatures", title: "Warm Darner" },
  { groupSlug: "totk_creatures", title: "White Goat" },
  { groupSlug: "totk_creatures", title: "White Pigeon" },
  { groupSlug: "w3_locations", title: "Abandoned Site" },
  { groupSlug: "w3_services", title: "Armorer" },
  { groupSlug: "w3_quests", title: "Hidden Treasure" },
  { groupSlug: "w3_items", title: "Book" },
  { groupSlug: "w3_other", title: "Miscellaneous" },
];
