export const regions = [
  //#region Black Myth Wukong
  {
    slug: "chapter-1",
    title: "Chapter 1: Black Cloud, Red Fire",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-1.png",
    tilePath: "black-myth-wukong/chapter-1",
    gameSlug: "black-myth-wukong",
    order: 1,
  },
  {
    slug: "chapter-2",
    title: "Chapter 2: Yellow Sand, Desolate Dusk",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-2.png",
    tilePath: "black-myth-wukong/chapter-2",
    gameSlug: "black-myth-wukong",
    order: 2,
  },
  {
    slug: "chapter-3",
    title: "Chapter 3: White Snow, Ice Cold",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-3.png",
    tilePath: "black-myth-wukong/chapter-3",
    gameSlug: "black-myth-wukong",
    order: 3,
  },
  {
    slug: "chapter-4",
    title: "Chapter 4: Rosy Cheeks, Gray Hair",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-4.png",
    tilePath: "black-myth-wukong/chapter-4",
    gameSlug: "black-myth-wukong",
    order: 4,
  },
  {
    slug: "chapter-5",
    title: "Chapter 5: Golden Child, Crimson Blood",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-5.png",
    tilePath: "black-myth-wukong/chapter-5",
    gameSlug: "black-myth-wukong",
    order: 5,
  },
  {
    slug: "06_huaguoshan",
    title: "Chapter 6",
    thumbnailUrl: "images/games/black-myth-wukong/06_huaguoshan.png",
    tilePath: "black-myth-wukong/06_huaguoshan",
    gameSlug: "black-myth-wukong",
    order: 6,
  },
  //#endregion

  //#region Tears of the Kingdom
  {
    slug: "hyrule",
    title: "Hyrule",
    thumbnailUrl: "images/games/zelda-tears-of-the-kingdom/hyrule.png",
    tilePath: "zelda-tears-of-the-kingdom/hyrule",
    gameSlug: "zelda-tears-of-the-kingdom",
    order: 1,
  },
  //#endregion

  //#region Elden Ring
  // {
  //   slug: "the-lands-between",
  //   title: "The Lands Between",
  //   thumbnailUrl: "thumbnails/the-lands-between.png",
  //   minZoom: 9,
  //   maxZoom: 16,
  //   zoom: 10,
  //   center: [0.65676201402282, -0.76234815932221],
  //   tilePath: "elden-ring/the-lands-between",
  //   gameSlug: "elden-ring",
  //   order: 1,
  // },
  // {
  //   slug: "the-shadow-realm",
  //   title: "Realm of Shadow",
  //   thumbnailUrl: "thumbnails/the-shadow-realm.png",
  //   minZoom: 8,
  //   maxZoom: 16,
  //   zoom: 10,
  //   center: [0.6685143165321, -0.72313106578409],
  //   tilePath: "elden-ring/the-shadow-lands",
  //   gameSlug: "elden-ring",
  //   order: 2,
  // },
  //#endregion

  //#region The Witcher 3
  // {
  //   slug: "white-orchard",
  //   title: "White Orchard",
  //   thumbnailUrl: "thumbnails/white-orchard.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/white-orchard",
  //   gameSlug: "witcher-3",
  //   order: 1,
  // },
  // {
  //   slug: "velen-novigrad",
  //   title: "Velen Novigrad",
  //   thumbnailUrl: "thumbnails/velen-novigrad.png",
  //   minZoom: 8,
  //   maxZoom: 14,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/velen-novigrad",
  //   gameSlug: "witcher-3",
  //   order: 2,
  // },
  // {
  //   slug: "skellige",
  //   title: "Skellige Isles",
  //   thumbnailUrl: "thumbnails/skellige.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/skellige",
  //   gameSlug: "witcher-3",
  //   order: 3,
  // },

  // {
  //   slug: "kaer-morhen",
  //   title: "Kaer Morhen",
  //   thumbnailUrl: "thumbnails/kaer-morhen.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/kaer-morhen",
  //   gameSlug: "witcher-3",
  //   order: 4,
  // },
  // {
  //   slug: "toussaint",
  //   title: "Toussaint",
  //   thumbnailUrl: "thumbnails/toussaint.png",
  //   minZoom: 8,
  //   maxZoom: 14,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/toussaint",
  //   gameSlug: "witcher-3",
  //   order: 5,
  // },
  // {
  //   slug: "fablesphere",
  //   title: "Fablesphere",
  //   thumbnailUrl: "thumbnails/fablesphere.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/fablesphere",
  //   gameSlug: "witcher-3",
  //   order: 6,
  // },
  // {
  //   slug: "isle-of-mists",
  //   title: "Isle of Mists",
  //   thumbnailUrl: "thumbnails/isle-of-mists.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/isle-of-mists",
  //   gameSlug: "witcher-3",
  //   order: 7,
  // },
  //#endregion
];
