export const regions = [
  //#region Black Myth Wukong
  {
    slug: "chapter-1",
    title: "Chapter 1",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-1.png",
    tilePath: "black-myth-wukong/chapter-1",
    gameSlug: "black-myth-wukong",
    order: 1,
  },
  {
    slug: "chapter-2",
    title: "Chapter 2",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-2.png",
    tilePath: "black-myth-wukong/chapter-2",
    gameSlug: "black-myth-wukong",
    order: 2,
  },
  {
    slug: "chapter-3",
    title: "Chapter 3",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-3.png",
    tilePath: "black-myth-wukong/chapter-3",
    gameSlug: "black-myth-wukong",
    order: 3,
  },
  {
    slug: "chapter-4",
    title: "Chapter 4",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-4.png",
    tilePath: "black-myth-wukong/chapter-4",
    gameSlug: "black-myth-wukong",
    order: 4,
  },
  {
    slug: "chapter-5",
    title: "Chapter 5",
    thumbnailUrl: "images/games/black-myth-wukong/chapter-5.png",
    tilePath: "black-myth-wukong/chapter-5",
    gameSlug: "black-myth-wukong",
    order: 5,
  },
  {
    slug: "04_zhujiadayuan",
    title: "Chapter 4 - Village of Lanxi",
    thumbnailUrl: "images/games/black-myth-wukong/04_zhujiadayuan.png",
    tilePath: "black-myth-wukong/04_zhujiadayuan",
    gameSlug: "black-myth-wukong",
    order: 6,
  },
  {
    slug: "04_pansidongshangceng",
    title: "Chapter 4 - Upper Webbed Hollow",
    thumbnailUrl: "images/games/black-myth-wukong/04_pansidongshangceng.png",
    tilePath: "black-myth-wukong/04_pansidongshangceng",
    gameSlug: "black-myth-wukong",
    order: 7,
  },
  {
    slug: "04_pansidongxiaceng",
    title: "Chapter 4 - Lower Webbed Hollow",
    thumbnailUrl: "images/games/black-myth-wukong/04_pansidongxiaceng.png",
    tilePath: "black-myth-wukong/04_pansidongxiaceng",
    gameSlug: "black-myth-wukong",
    order: 8,
  },
  {
    slug: "04_huanghuaguan",
    title: "Chapter 4 - Temple of Yellow Flowers",
    thumbnailUrl: "images/games/black-myth-wukong/04_huanghuaguan.png",
    tilePath: "black-myth-wukong/04_huanghuaguan",
    gameSlug: "black-myth-wukong",
    order: 9,
  },
  {
    slug: "04_ziyunshan",
    title: "Chapter 4 - Purple Cloud Mountain",
    thumbnailUrl: "images/games/black-myth-wukong/04_ziyunshan.png",
    tilePath: "black-myth-wukong/04_ziyunshan",
    gameSlug: "black-myth-wukong",
    order: 10,
  },
  {
    slug: "05_huoyanshan",
    title: "Chapter 5: Flaming Mountains",
    thumbnailUrl: "images/games/black-myth-wukong/05_huoyanshan.png",
    tilePath: "black-myth-wukong/05_huoyanshan",
    gameSlug: "black-myth-wukong",
    order: 11,
  },
  {
    slug: "06_huaguoshan",
    title: "Chapter 6: Mount Huaguo",
    thumbnailUrl: "images/games/black-myth-wukong/06_huaguoshan.png",
    tilePath: "black-myth-wukong/06_huaguoshan",
    gameSlug: "black-myth-wukong",
    order: 12,
  },
  //#endregion

  //#region Tears of the Kingdom
  // {
  //   slug: "hyrule",
  //   title: "Hyrule",
  //   thumbnailUrl: "thumbnails/hyrule.png",
  //   minZoom: 9,
  //   maxZoom: 16,
  //   zoom: 10,
  //   center: [0.70760348036569, -0.71764231663026],
  //   tilePath: "totk/hyrule",
  //   gameSlug: "totk",
  //   order: 1
  // },
  //#endregion

  //#region Elden Ring
  // {
  //   slug: "the-lands-between",
  //   title: "The Lands Between",
  //   thumbnailUrl: "thumbnails/the-lands-between.png",
  //   minZoom: 9,
  //   maxZoom: 16,
  //   zoom: 10,
  //   center: [0.65676201402282, -0.76234815932221],
  //   tilePath: "elden-ring/the-lands-between",
  //   gameSlug: "elden-ring",
  //   order: 1,
  // },
  // {
  //   slug: "the-shadow-realm",
  //   title: "Realm of Shadow",
  //   thumbnailUrl: "thumbnails/the-shadow-realm.png",
  //   minZoom: 8,
  //   maxZoom: 16,
  //   zoom: 10,
  //   center: [0.6685143165321, -0.72313106578409],
  //   tilePath: "elden-ring/the-shadow-lands",
  //   gameSlug: "elden-ring",
  //   order: 2,
  // },
  //#endregion

  //#region The Witcher 3
  // {
  //   slug: "white-orchard",
  //   title: "White Orchard",
  //   thumbnailUrl: "thumbnails/white-orchard.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/white-orchard",
  //   gameSlug: "witcher-3",
  //   order: 1,
  // },
  // {
  //   slug: "velen-novigrad",
  //   title: "Velen Novigrad",
  //   thumbnailUrl: "thumbnails/velen-novigrad.png",
  //   minZoom: 8,
  //   maxZoom: 14,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/velen-novigrad",
  //   gameSlug: "witcher-3",
  //   order: 2,
  // },
  // {
  //   slug: "skellige",
  //   title: "Skellige Isles",
  //   thumbnailUrl: "thumbnails/skellige.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/skellige",
  //   gameSlug: "witcher-3",
  //   order: 3,
  // },

  // {
  //   slug: "kaer-morhen",
  //   title: "Kaer Morhen",
  //   thumbnailUrl: "thumbnails/kaer-morhen.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/kaer-morhen",
  //   gameSlug: "witcher-3",
  //   order: 4,
  // },
  // {
  //   slug: "toussaint",
  //   title: "Toussaint",
  //   thumbnailUrl: "thumbnails/toussaint.png",
  //   minZoom: 8,
  //   maxZoom: 14,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/toussaint",
  //   gameSlug: "witcher-3",
  //   order: 5,
  // },
  // {
  //   slug: "fablesphere",
  //   title: "Fablesphere",
  //   thumbnailUrl: "thumbnails/fablesphere.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/fablesphere",
  //   gameSlug: "witcher-3",
  //   order: 6,
  // },
  // {
  //   slug: "isle-of-mists",
  //   title: "Isle of Mists",
  //   thumbnailUrl: "thumbnails/isle-of-mists.png",
  //   minZoom: 8,
  //   maxZoom: 12,
  //   zoom: 9,
  //   center: [83.937238401332, -168.44211701243],
  //   tilePath: "witcher-3/isle-of-mists",
  //   gameSlug: "witcher-3",
  //   order: 7,
  // },
  //#endregion
];
