export const categories = [
  {
    markerGroupId: 177,
    title: "Dragon Shrine",
    icon: "dragon_shrine",
    info: "",
    template:
      "**Location:** ??  \n**Utility:** Learn new Dragon Communion incantations in exchange for Dragon Hearts.\n**Inventory:**\n- ??",
  },
  {
    markerGroupId: 177,
    title: "Dungeon",
    icon: "dungeon",
    info: null,
    template: "**Boss:** ??  \n\n**Notable Items:**\n- ??",
  },
  {
    markerGroupId: 177,
    title: "Elevator",
    icon: "elevator",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Evergaol",
    icon: "evergaol",
    info: null,
    template: "**Boss:** ??",
  },
  {
    markerGroupId: 177,
    title: "Hidden Passage",
    icon: "hidden_passage",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Imp Seal Statue",
    icon: "imp_seal_statue",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Landmark",
    icon: "landmark",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Legacy Dungeon",
    icon: "legacy_dungeon",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Martyr Effigy",
    icon: "martyr_effigy",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Minor Erdtree",
    icon: "minor_erdtree",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Portal",
    icon: "portal",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Site of Grace",
    icon: "site_of_grace",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Smithing Table",
    icon: "smithing_table",
    info: null,
    template: "Used to upgrade armaments.  \nLocation: ??",
  },
  {
    markerGroupId: 177,
    title: "Spiritspring Jump",
    icon: "spiritspring_jump",
    info: null,
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Stake of Marika",
    icon: "stake_of_marika",
    info: "Upon dying within the vicinity of a Stake of Marika, you may choose to respawn there instead of a Site of Grace.",
    template: null,
  },
  {
    markerGroupId: 177,
    title: "Wandering Mausoleum",
    icon: "wandering_mausoleum",
    info: null,
    template: null,
  },
  {
    markerGroupId: 178,
    title: "Bell Bearing",
    icon: "bell_bearing",
    info: null,
    template:
      "**Related Merchant:** ??  \n**Utility:** Unlocks the related merchant's inventory at the [Twin Maiden Husks](https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167787).",
  },
  {
    markerGroupId: 178,
    title: "Cookbook",
    icon: "cookbook",
    info: null,
    template: "**Location:** ??  \n**Recipes:**\n- ??",
  },
  {
    markerGroupId: 178,
    title: "Cracked Pot",
    icon: "cracked_pot",
    info: null,
    template: null,
  },
  {
    markerGroupId: 178,
    title: "Great Rune",
    icon: "great_rune",
    info: null,
    template: "**Location:** ??  \n**Effect:** ??  \n**Related Tower:** ??",
  },
  {
    markerGroupId: 178,
    title: "Key Item",
    icon: "key_item",
    info: null,
    template: "**Location:** ??  \n**Utility:** ??",
  },
  {
    markerGroupId: 178,
    title: "Map Fragment",
    icon: "map_fragment",
    info: null,
    template: "**Location:** ??",
  },
  {
    markerGroupId: 178,
    title: "Memory Stone",
    icon: "memory_stone",
    info: null,
    template:
      "**Location:** ??  \n**Utility:** Increases the number of available spell slots.",
  },
  {
    markerGroupId: 178,
    title: "Painting",
    icon: "painting",
    info: null,
    template:
      "**Painting Location:** ??  \n**Reward:** ??  \n\nAfter interacting with the painting, go to the Reward's location and interact with the ghost. This ghost will not spawn until you have interacted with the painting.",
  },
  {
    markerGroupId: 178,
    title: "Perfume Bottle",
    icon: "perfume_bottle",
    info: null,
    template: null,
  },
  {
    markerGroupId: 178,
    title: "Remembrance",
    icon: "remembrance",
    info: null,
    template:
      "**Boss:** ??  \n**Value:** ?? Runes  \n**Trades for:**\n- ?? or\n- ??",
  },
  {
    markerGroupId: 178,
    title: "Ritual Pot",
    icon: "ritual_pot",
    info: null,
    template: null,
  },
  {
    markerGroupId: 178,
    title: "Spellbook",
    icon: "spellbook",
    info: null,
    template:
      "**Location:** ??  \n**Utility:** Bring to ?? or ?? to unlock the following ??:\n- ??",
  },
  {
    markerGroupId: 178,
    title: "Stonesword Key",
    icon: "stonesword_key",
    info: null,
    template: null,
  },
  {
    markerGroupId: 178,
    title: "Talisman Pouch",
    icon: "talisman_pouch",
    info: null,
    template:
      "**Location:** ??  \n**Utility:** Increases the number of talismans you can carry.",
  },
  {
    markerGroupId: 178,
    title: "Tool",
    icon: "tool",
    info: null,
    template: "**Location:** ??  \n**Utility:** ??",
  },
  {
    markerGroupId: 178,
    title: "Whetblade",
    icon: "whetblade",
    info: null,
    template: "**Location:** ??  \n**Utility:** ??",
  },
  {
    markerGroupId: 179,
    title: "Ammunition",
    icon: "ammunition",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Cerulean Scarab",
    icon: "cerulean_scarab",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Consumable",
    icon: "consumable",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Crimson Scarab",
    icon: "teardrop_scarab",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Crystal Tear",
    icon: "crystal_tear",
    info: "**How to use:** At any Site of Grace, combine with another Crystal Tear in the [Flask of Wondrous Physique](https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=164723). Lasts for 3 minutes unless otherwise noted.",
    template: "**Location:** ??  \n**Effect granted:** ??",
  },
  {
    markerGroupId: 179,
    title: "Deathroot",
    icon: "deathroot",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Dragon Heart",
    icon: "dragon_heart",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Gesture",
    icon: "gesture",
    info: null,
    template: "**Location:** ??",
  },
  {
    markerGroupId: 179,
    title: "Golden Rune",
    icon: "golden_rune",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Golden Seed",
    icon: "golden_seed",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Item",
    icon: "item",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Larval Tear",
    icon: "sacred_tear",
    info: "**Utility:** Trade to [Rennala](https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=165895) to gain rebirth and reallocate attribute points.",
    template: "**Location:** ??",
  },
  {
    markerGroupId: 179,
    title: "Multiplayer Item",
    icon: "multiplayer_item",
    info: null,
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Rune Arc",
    icon: "rune_arc",
    info: null,
    template:
      "**Location:** ??  \n**Utility:** Consume to activate a Great Rune's power. Lasts until you die.",
  },
  {
    markerGroupId: 179,
    title: "Sacred Tear",
    icon: "sacred_tear",
    info: "**Utility:** Consume at a Site of Grace to upgrade the Flask of Crimson Tears and the Flask of Cerulean Tears.",
    template: null,
  },
  {
    markerGroupId: 179,
    title: "Spirit Ashes",
    icon: "spirit_ashes",
    info: "**Spirit Ashes** are summonable companions, that can aid the player in combat. After receiving the [Spirit Calling Bell](https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=167800), the player may summon any acquired Spirit Ash by paying its cost when in range of a Rebirth Monument.\n\nAfter completing Roderika's Task, [Roderika](https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=170232) can upgrade any Spirit Ash with the corresponding upgrade material, up to +10.",
    template:
      "**Location:** ??  \n**Summoned creature(s):** ??  \n**Cost:** ??  \n**Upgrade Material:** ??",
  },
  {
    markerGroupId: 180,
    title: "Armor",
    icon: "armor",
    info: null,
    template: "**Location:** ??  \n**Armor:**\n- ??",
  },
  {
    markerGroupId: 180,
    title: "Ash of War",
    icon: "ash_of_war",
    info: null,
    template:
      "**Location:** ??  \n**Granted Affinity:** ??  \n**Appliable to:**\n- ??",
  },
  {
    markerGroupId: 180,
    title: "Incantation",
    icon: "incantation",
    info: null,
    template: "**Location:** ??  \n**Spell Type:** ??",
  },
  {
    markerGroupId: 180,
    title: "Shield",
    icon: "shield",
    info: null,
    template: "**Location:** ??  \n**Type:** ??  \n**Skill:** ??",
  },
  {
    markerGroupId: 180,
    title: "Sorcery",
    icon: "sorcery",
    info: null,
    template: "**Location:** ??  \n**Spell Type:** ??",
  },
  {
    markerGroupId: 180,
    title: "Talisman",
    icon: "talisman",
    info: null,
    template: "**Location:** ??  \n**Effect:** ??",
  },
  {
    markerGroupId: 180,
    title: "Weapon",
    icon: "weapon",
    info: null,
    template: "**Location:** ??  \n**Type:** ??  \n**Weapon Skill:** ??",
  },
  {
    markerGroupId: 181,
    title: "Character",
    icon: "character",
    info: null,
    template: "**Location:** ??  \n**Quest:** ??",
  },
  {
    markerGroupId: 181,
    title: "Ghost",
    icon: "ghost",
    info: null,
    template: null,
  },
  {
    markerGroupId: 181,
    title: "Merchant",
    icon: "merchant",
    info: null,
    template:
      "**Location:** ??  \n**Inventory (unique):**\n- ??\n\n**Inventory (other):**\n- ??\n\n**Other:**\n- ??",
  },
  {
    markerGroupId: 181,
    title: "Trainer",
    icon: "trainer",
    info: null,
    template: null,
  },
  {
    markerGroupId: 182,
    title: "Boss",
    icon: "boss",
    info: null,
    template: "**Location:** ??  \n**Loot:**\n- ??",
  },
  {
    markerGroupId: 182,
    title: "Elite Enemy",
    icon: "elite_enemy",
    info: null,
    template: "**Location:** ??  \n**Loot:** ??",
  },
  {
    markerGroupId: 182,
    title: "Enemy",
    icon: "enemy",
    info: null,
    template: null,
  },
  {
    markerGroupId: 182,
    title: "Great Boss",
    icon: "great_boss",
    info: null,
    template: "**Location:** ??  \n**Reward:** ??",
  },
  {
    markerGroupId: 182,
    title: "Invasion",
    icon: "invasion",
    info: null,
    template: "**Location:** ??  \n**Loot:**\n- ??",
  },
  {
    markerGroupId: 182,
    title: "Legendary Boss",
    icon: "demigod",
    info: null,
    template: "**Location:** ??  \n**Loot:** ??",
  },
  {
    markerGroupId: 183,
    title: "Ancient Smithing Stone",
    icon: "ancient_smithing_stone",
    info: null,
    template: "**Location:** ??",
  },
  {
    markerGroupId: 183,
    title: "Crafting Material",
    icon: "crafting_material",
    info: null,
    template: null,
  },
  {
    markerGroupId: 183,
    title: "Ghost Glovewort",
    icon: "ghost_glovewort",
    info: null,
    template: null,
  },
  {
    markerGroupId: 183,
    title: "Glovewort",
    icon: "glovewort",
    info: "**Utility:** Give to [Roderika](https://mapgenie.io/elden-ring/maps/the-lands-between?locationIds=170232) to upgrade Spirit Ashes.  \n- A Grave Glovewort [X] upgrades a standard Spirit Ash to +X.\n- A Ghost Glovewort [X] upgrades an elite Spirit Ash to +X.",
    template: "**Location:** ??",
  },
  {
    markerGroupId: 183,
    title: "Great Glovewort",
    icon: "great_glovewort",
    info: null,
    template: null,
  },
  {
    markerGroupId: 183,
    title: "Miquella's Lily",
    icon: "miquellas_lilly",
    info: null,
    template: null,
  },
  {
    markerGroupId: 183,
    title: "Ruin Fragment",
    icon: "ruin_fragment",
    info: null,
    template: null,
  },
  {
    markerGroupId: 183,
    title: "Smithing Stone",
    icon: "smithing_stone",
    info: null,
    template: null,
  },
  {
    markerGroupId: 183,
    title: "Trina's Lilly",
    icon: "trinas_lilly",
    info: null,
    template: null,
  },
  {
    markerGroupId: 184,
    title: "Birdseye Telescope",
    icon: "birdseye_telescope",
    info: null,
    template: null,
  },
  {
    markerGroupId: 184,
    title: "Guiding Statue",
    icon: "guiding_statue",
    info: null,
    template: null,
  },
  {
    markerGroupId: 184,
    title: "Lore",
    icon: "lore",
    info: null,
    template: null,
  },
  {
    markerGroupId: 184,
    title: "Miscellaneous",
    icon: "miscellaneous",
    info: null,
    template: null,
  },
  {
    markerGroupId: 184,
    title: "Puzzle",
    icon: "puzzle",
    info: null,
    template: null,
  },
  {
    markerGroupId: 184,
    title: "Quest",
    icon: "quest",
    info: null,
    template: "**How to Begin:** ??  \n**Steps:**\n1. ??",
  },
  {
    markerGroupId: 184,
    title: "Summoning Sigil",
    icon: "summoning_sigil",
    info: null,
    template: "**Related Boss:** ??",
  },
];
